import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'

interface FileMap {
  [key: string]: string
}

// Mock AI code generation - in production, integrate with OpenAI or similar
async function generateCode(prompt: string, type: string): Promise<FileMap> {
  // This is a placeholder for AI integration
  // In production, you would call OpenAI API or another AI service
  
  const templates: Record<string, FileMap> = {
    'website': {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; }
        .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 100px 20px; text-align: center; }
        .hero h1 { font-size: 3rem; margin-bottom: 20px; }
        .hero p { font-size: 1.2rem; margin-bottom: 30px; }
        .btn { display: inline-block; padding: 12px 30px; background: white; color: #667eea; text-decoration: none; border-radius: 5px; font-weight: bold; }
        .features { padding: 80px 20px; max-width: 1200px; margin: 0 auto; }
        .feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 30px; margin-top: 40px; }
        .feature { padding: 30px; background: #f8f9fa; border-radius: 10px; }
        .feature h3 { color: #667eea; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="hero">
        <h1>${prompt}</h1>
        <p>Welcome to your new website generated by AI</p>
        <a href="#features" class="btn">Learn More</a>
    </div>
    <div class="features" id="features">
        <h2 style="text-align: center; font-size: 2.5rem; margin-bottom: 20px;">Features</h2>
        <div class="feature-grid">
            <div class="feature">
                <h3>Fast & Modern</h3>
                <p>Built with the latest web technologies for optimal performance.</p>
            </div>
            <div class="feature">
                <h3>Responsive Design</h3>
                <p>Looks great on all devices, from mobile to desktop.</p>
            </div>
            <div class="feature">
                <h3>Easy to Customize</h3>
                <p>Simple code structure makes it easy to modify and extend.</p>
            </div>
        </div>
    </div>
</body>
</html>`,
      'styles.css': `/* Additional styles can be added here */`,
    },
    'landing-page': {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt} - Landing Page</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
        .navbar { background: white; padding: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); position: sticky; top: 0; z-index: 100; }
        .hero { min-height: 90vh; display: flex; align-items: center; justify-content: center; background: linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%); color: white; text-align: center; padding: 20px; }
        .hero h1 { font-size: 4rem; margin-bottom: 20px; }
        .cta-button { display: inline-block; padding: 15px 40px; background: white; color: #3b82f6; text-decoration: none; border-radius: 50px; font-weight: bold; font-size: 1.2rem; margin-top: 20px; }
        .features { padding: 100px 20px; background: #f9fafb; }
        .container { max-width: 1200px; margin: 0 auto; }
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="container" style="display: flex; justify-content: space-between; align-items: center;">
            <h2>${prompt}</h2>
            <a href="#cta" class="cta-button" style="padding: 10px 25px; font-size: 1rem;">Get Started</a>
        </div>
    </nav>
    <section class="hero">
        <div>
            <h1>${prompt}</h1>
            <p style="font-size: 1.5rem; margin-bottom: 30px;">Transform your ideas into reality with our powerful solution</p>
            <a href="#cta" class="cta-button">Start Free Trial</a>
        </div>
    </section>
    <section class="features">
        <div class="container">
            <h2 style="text-align: center; font-size: 3rem; margin-bottom: 60px;">Why Choose Us?</h2>
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 40px;">
                <div style="text-align: center; padding: 30px;">
                    <h3 style="font-size: 1.8rem; margin-bottom: 15px;">Fast Setup</h3>
                    <p>Get started in minutes, not hours</p>
                </div>
                <div style="text-align: center; padding: 30px;">
                    <h3 style="font-size: 1.8rem; margin-bottom: 15px;">Powerful Features</h3>
                    <p>Everything you need to succeed</p>
                </div>
                <div style="text-align: center; padding: 30px;">
                    <h3 style="font-size: 1.8rem; margin-bottom: 15px;">24/7 Support</h3>
                    <p>We're always here to help</p>
                </div>
            </div>
        </div>
    </section>
</body>
</html>`,
    },
    'react-app': {
      'App.jsx': `import React, { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <h1>${prompt}</h1>
        <p>A React application generated by AI</p>
        <div className="counter">
          <button onClick={() => setCount(count - 1)}>-</button>
          <span className="count">{count}</span>
          <button onClick={() => setCount(count + 1)}>+</button>
        </div>
      </header>
    </div>
  );
}

export default App;`,
      'App.css': `.App {
  text-align: center;
}

.App-header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}

.counter {
  display: flex;
  align-items: center;
  gap: 20px;
  margin-top: 30px;
}

.counter button {
  font-size: 2rem;
  padding: 10px 20px;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  background: white;
  color: #667eea;
  font-weight: bold;
}

.count {
  font-size: 3rem;
  min-width: 80px;
}`,
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt}</title>
</head>
<body>
    <div id="root"></div>
</body>
</html>`,
    },
    'admin-panel': {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt} - Admin Panel</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; }
        .container { display: flex; height: 100vh; }
        .sidebar { width: 250px; background: #1e293b; color: white; padding: 20px; }
        .sidebar h2 { margin-bottom: 30px; }
        .sidebar ul { list-style: none; }
        .sidebar li { padding: 12px; margin: 5px 0; border-radius: 5px; cursor: pointer; }
        .sidebar li:hover { background: #334155; }
        .main { flex: 1; padding: 30px; overflow-y: auto; }
        .header { background: white; padding: 20px; border-radius: 10px; margin-bottom: 30px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .stat-card { background: white; padding: 25px; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
        .stat-card h3 { color: #64748b; font-size: 0.9rem; margin-bottom: 10px; }
        .stat-card .value { font-size: 2rem; font-weight: bold; color: #1e293b; }
        table { width: 100%; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
        th, td { padding: 15px; text-align: left; }
        th { background: #f8fafc; font-weight: 600; }
        tr { border-bottom: 1px solid #e2e8f0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <h2>Admin Panel</h2>
            <ul>
                <li>📊 Dashboard</li>
                <li>👥 Users</li>
                <li>📝 Projects</li>
                <li>⚙️ Settings</li>
                <li>📊 Analytics</li>
            </ul>
        </div>
        <div class="main">
            <div class="header">
                <h1>${prompt}</h1>
                <p>Welcome back! Here's what's happening today.</p>
            </div>
            <div class="stats">
                <div class="stat-card">
                    <h3>Total Users</h3>
                    <div class="value">1,234</div>
                </div>
                <div class="stat-card">
                    <h3>Active Projects</h3>
                    <div class="value">567</div>
                </div>
                <div class="stat-card">
                    <h3>Revenue</h3>
                    <div class="value">$12,345</div>
                </div>
                <div class="stat-card">
                    <h3>Growth</h3>
                    <div class="value">+23%</div>
                </div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>John Doe</td>
                        <td>john@example.com</td>
                        <td>Active</td>
                        <td>2024-01-15</td>
                    </tr>
                    <tr>
                        <td>Jane Smith</td>
                        <td>jane@example.com</td>
                        <td>Active</td>
                        <td>2024-01-14</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>`,
    },
    'presentation': {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt} - Presentation</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; overflow: hidden; }
        .slide { height: 100vh; display: none; align-items: center; justify-content: center; padding: 80px; text-align: center; }
        .slide.active { display: flex; }
        .slide-1 { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
        .slide-2 { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; }
        .slide-3 { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; }
        h1 { font-size: 5rem; margin-bottom: 30px; }
        p { font-size: 2rem; }
        .controls { position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%); display: flex; gap: 20px; }
        .controls button { padding: 15px 30px; font-size: 1rem; border: none; border-radius: 50px; cursor: pointer; background: white; font-weight: bold; }
    </style>
</head>
<body>
    <div class="slide slide-1 active">
        <div>
            <h1>${prompt}</h1>
            <p>A Modern Presentation</p>
        </div>
    </div>
    <div class="slide slide-2">
        <div>
            <h1>Key Features</h1>
            <p>• Beautiful Design<br>• Easy to Navigate<br>• Fully Customizable</p>
        </div>
    </div>
    <div class="slide slide-3">
        <div>
            <h1>Thank You!</h1>
            <p>Questions?</p>
        </div>
    </div>
    <div class="controls">
        <button onclick="prevSlide()">← Previous</button>
        <button onclick="nextSlide()">Next →</button>
    </div>
    <script>
        let currentSlide = 0;
        const slides = document.querySelectorAll('.slide');
        
        function showSlide(n) {
            slides.forEach(slide => slide.classList.remove('active'));
            currentSlide = (n + slides.length) % slides.length;
            slides[currentSlide].classList.add('active');
        }
        
        function nextSlide() { showSlide(currentSlide + 1); }
        function prevSlide() { showSlide(currentSlide - 1); }
        
        document.addEventListener('keydown', (e) => {
            if (e.key === 'ArrowRight') nextSlide();
            if (e.key === 'ArrowLeft') prevSlide();
        });
    </script>
</body>
</html>`,
    }
  };

  return templates[type] || templates['website'];
}

export async function POST(req: NextRequest) {
  try {
    const session = await auth()
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { prompt, type } = await req.json()

    if (!prompt || !type) {
      return NextResponse.json(
        { error: 'Prompt and type are required' },
        { status: 400 }
      )
    }

    // Generate code using AI (mocked for now)
    const code = await generateCode(prompt, type)

    return NextResponse.json({
      success: true,
      code,
      message: 'Code generated successfully'
    })

  } catch (error) {
    console.error('Error generating code:', error)
    return NextResponse.json(
      { error: 'Failed to generate code' },
      { status: 500 }
    )
  }
}
