import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import archiver from 'archiver'

export async function POST(req: NextRequest) {
  try {
    const session = await auth()
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { files, projectName } = await req.json()

    if (!files || typeof files !== 'object') {
      return NextResponse.json(
        { error: 'Files object is required' },
        { status: 400 }
      )
    }

    // Create a zip archive
    const archive = archiver('zip', {
      zlib: { level: 9 }
    })

    // Collect chunks
    const chunks: Buffer[] = []
    
    // Set up event listeners BEFORE finalizing
    archive.on('data', (chunk: Buffer) => chunks.push(chunk))
    
    const archivePromise = new Promise<void>((resolve, reject) => {
      archive.on('end', resolve)
      archive.on('error', reject)
    })

    // Add files to the archive
    Object.entries(files).forEach(([filename, content]) => {
      archive.append(content as string, { name: filename })
    })

    // Add a README
    archive.append(
      `# ${projectName || 'Project'}\n\nGenerated by AI Builder\n\nTo run this project:\n1. Extract all files\n2. Open index.html in a browser\n`, 
      { name: 'README.md' }
    )

    // Finalize the archive
    await archive.finalize()
    
    // Wait for archive to complete
    await archivePromise

    const buffer = Buffer.concat(chunks)
    const base64 = buffer.toString('base64')

    return NextResponse.json({
      success: true,
      zip: base64,
      filename: `${projectName || 'project'}.zip`
    })

  } catch (error) {
    console.error('Error creating zip:', error)
    return NextResponse.json(
      { error: 'Failed to create zip file' },
      { status: 500 }
    )
  }
}
